### ISSUE TITLE
bump.fs artifacts at boundaries

### ISSUE THREAD

**Issue by buencons** [dilevin/computer-graphics-shader-pipeline#10]
Hi,

I am seeing some artifacts at boundaries when generating bumps on my sphere.
![bump](https://user-images.githubusercontent.com/19580484/54081882-0fb46200-42e3-11e9-9e57-7b679535f917.PNG)

I only see this happen when I try to increase the frequency of my Perlin noise function.
Has anyone else seen this issue?

Thanks.

**Comment by ACalza** [comment]
Are you approximating your tangent vector? I seem to be getting that issue too, however it goes away when I hard code my tangent vector.

<img width="493" alt="image" src="https://user-images.githubusercontent.com/3921291/54091356-a6216b80-4355-11e9-8630-52b676a1ffe2.png">

**Comment by buencons** [comment]
Fixed this issue. My perlin noise function was incorrect. I assumed casting from float to int would automatically floor a number but I guess not. Here is how it looks now:
![nice](https://user-images.githubusercontent.com/19580484/54092722-c35e3600-4365-11e9-9f00-77f42557f648.PNG)
