### ISSUE TITLE
Phong shading not shading correctly (and noise in centre) bump map

### ISSUE THREAD

**Issue by csc418-anon** [dilevin/computer-graphics-shader-pipeline#11]
I have a directional light coming from the top left, so the bottom right of the sphere should be dark, yet it isn't.

I also have a bit of noise right in the centre, not sure why, but when you rotate it it's not there, it's just that specific part of the sphere.

But my biggest issue is the lighting, where it's lighting more of the sphere than it should.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/48340920/54094238-d2e57b00-4375-11e9-8733-412cd7859768.png">

This is supposed to be the 'back', yet there is lighting. I tried debugging the Normals without bumps, and it passes all the checkmarks, even the Perlin Noise seems to be colouring things in correctly. Any suggestions? 

<img width="397" alt="image" src="https://user-images.githubusercontent.com/48340920/54094261-0a542780-4376-11e9-9d2d-362bd9ba8d54.png">

**Comment by rarora7777** [comment]
Does your Blinn-Phong sphere (without noise) look okay?

Also, since you are using a directional light, it is possible that the Perlin-noised normals on these parts of the sphere actually have a positive dot product with the light direction. So your result may be completely correct.

If the answer to the first question is yes, and you're sure that the result you have posted is incorrect, then please post a result which **doesn't** use Perlin noise for the kd, ka, etc. and I can try to help out more.

**Comment by csc418-anon** [comment]
Thank you for the response, genuinely appreciate it! 

This was with Perlin Noise but no bumps (JSON -06
<img width="544" alt="image" src="https://user-images.githubusercontent.com/48340920/54140599-5ea0eb00-43fa-11e9-89ea-410e48ca3d52.png">

I just noticed there's weird discontinuation lines as shown in this image, however the overall sphere is 'okay'



This is the image w/o Perlin Noise, and just the bumps:

When I zoom in really closely, the noise appears, when I zoom out, it disappears
<img width="412" alt="image" src="https://user-images.githubusercontent.com/48340920/54142185-90678100-43fd-11e9-9a5c-8b3b83b35789.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/48340920/54142223-a5441480-43fd-11e9-8adc-6d1bd4fa2899.png">

Anyways any suggestion is much appreciated!

**Comment by rin-23** [comment]
regarding your light problem.
when passing view, normal and light vectors to blingphong function you need to make sure they are in the same space (view space for example).

**Comment by rin-23** [comment]
Try fixing the light first and see if that gets rid of noise.

**Comment by csc418-anon** [comment]
So it looks like this: 

<img width="429" alt="image" src="https://user-images.githubusercontent.com/48340920/54142828-e7ba2100-43fe-11e9-8043-687ebeed19d0.png">

It still looks slightly off on the lit part. The noise seems to be gone.

EDIT: 

<img width="204" alt="image" src="https://user-images.githubusercontent.com/48340920/54143252-d7567600-43ff-11e9-8e14-c3980240a13a.png">

vs 

<img width="192" alt="image" src="https://user-images.githubusercontent.com/48340920/54143263-dcb3c080-43ff-11e9-9807-c8977654b5f6.png">

Another edit, 

This is the lighting, kind of a given point close up, but kind of expected I assume?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/48340920/54143412-28666a00-4400-11e9-9222-417489fa3dd5.png">

And lastly, when I change my height function (still returns -0.1-0.1). But the zooming in/out issue is fixed now. 

<img width="309" alt="image" src="https://user-images.githubusercontent.com/48340920/54143604-8e52f180-4400-11e9-838d-d029e401999b.png">

**Comment by csc418-anon** [comment]
@rin-23 Thank you for your help. 

For those that run into a similar issue: 
So basically I a lot went wrong when producing the bump maps, firstly I didn't update my point to view space, which was a major issue. 

Secondly, I was using a sin function to determine the bump height with the noise, and it just looks awkward, and off, so I just removed it, and started playing with the frequency inside the noise to create literal bumps of terrain (similar to those in the gif). 

Thanks again @rin-23  for the response, cheers.
