### ISSUE TITLE
test-02 weird translations

### ISSUE THREAD

**Issue by alexei-zolotarevschi** [dilevin/computer-graphics-shader-pipeline#14]
I was getting wonky behavior in test2, so I messed around with my model.glsl to only apply 1 transformation to the moon at a time, and translating seems to be the culprit. I compared the matrix to the slides and am pretty sure that translate.glsl is correct. Does this look familiar to anyone?
![Untitled](https://user-images.githubusercontent.com/15279316/54174608-2800ba00-4466-11e9-884c-92b251e71223.png)
![Untitled1](https://user-images.githubusercontent.com/15279316/54174609-2800ba00-4466-11e9-8b5b-a412e8045bd7.png)

**Comment by AllenLXL** [comment]
Have you try to add transpose to translation matrix? Glsl is using col-major order.

**Comment by alexei-zolotarevschi** [comment]
Worked like a charm, thanks. Not sure how I haven't noticed this before.
