### ISSUE TITLE
Significance of range of improved perlin noise

### ISSUE THREAD

**Issue by IgorStempen** [dilevin/computer-graphics-shader-pipeline#16]
Hi,

I was just wondering why the improved perlin noise must have an output range of -1/2 to 1/2? Is this a strict requirment?

**Comment by rarora7777** [comment]
I think it's just a typo. I'll confirm with Rinat as well and let you know if there's any significance to it.

**Comment by rin-23** [comment]
I also think its a typo. You can return (-1,1) instead same as perlin_noise function.  
In the end you can always rescale the returned value to generate the results you want.

**Comment by ACalza** [comment]
Oh lmao, I was returning -0.5, 0.5, too late already submitted, didn't change much. Won't matter I presume?
