### ISSUE TITLE
debugging coordinates

### ISSUE THREAD

**Issue by yeqingxi** [dilevin/computer-graphics-shader-pipeline#18]
I'm currently stuck on snap_to_sphere.tes since nothing is showing on the screen, is there a way to print out the coordinates to help me debug?

**Comment by WChrisK** [comment]
Have you tried [this](https://bb-2019-01.teach.cs.toronto.edu/t/a-way-for-you-to-sanely-debug-shaders-for-those-who-are-stuck/1042)?

**Comment by rin-23** [comment]
are you sure you are populating gl_Position value?

**Comment by yeqingxi** [comment]
Yeah it turns out I forgot to set the gl_Position value, thanks a bunch!
