### ISSUE TITLE
Shall we apply function composition in bump_height or bump_position? 

### ISSUE THREAD

**Issue by jwmaggiezhou** [dilevin/computer-graphics-shader-pipeline#19]
Like in proedural_color, all the scaling happens within the fragment shader, but for the bump part, are we allowed to manipulate the input in bump_height or bump_position or all the manipulation should also happen in bump.fs?

**Comment by rarora7777** [comment]
You can perform these manipulations wherever you see fit. Any of those three is acceptable to us.
