### ISSUE TITLE
Translation in Model.glsl

### ISSUE THREAD

**Issue by Geetchopra** [dilevin/computer-graphics-shader-pipeline#20]
I don't know what I am missing when applying a translation to the moon. If we need to hardcode the values of t what kind of values are we expected to input, and is it a uniform translation? The reason I ask is because even a value of 0.1 seems to only translate one corner of the moon. Also, will fixing the translation fix the moon not going "behind" the earth or is that another problem?

This is the current output without any translation, and with another hardcoded value to shift the origin of the moon around which it rotates. Please excuse the poor quality gif, its only a recording issue, it runs smoothly on my system.

![debug](https://user-images.githubusercontent.com/12212222/54390435-d8dea300-4678-11e9-9465-085f5153ea16.gif)

**Comment by rin-23** [comment]
It seems like your pivot point of rotation is in front of the big sphere and radius of rotation is small so it never actually goes behind. 
I assume the issue is with you model.glsl
What is the order of scaling, translation and rotation in your case?
you might be applying translation and rotation in the wrong order.

**Comment by Geetchopra** [comment]
I am doing rotation * translation in model.glsl and in model_view_projection.glsl I'm calculating scale*projection*view*model*point.
Also in the above gif the translation vector is 0,0,0.

**Comment by rin-23** [comment]
so you are applying rotation and translation  twice?

model.glsl computes model matrix. Model matrix is a combination of scaling(S), translation(T) and rotation (R). Order of these operations matters. Make sure you figure out the correct order.

model_view_projection.vs
takes a point and transforms it into screen space.
To do that you need to transform the point into view space first using model (calculated using model.glsl) and view matrcies and finally bring it into screen space using proj matrix.

**Comment by Geetchopra** [comment]
Fixing the order seemed to fix the issue, however in this output there is still no translation but it basically looks like the gif in the assignment handout. The only different is that the rotation is counter-clockwise instead of clockwise. Do I need to fix the rotation (and how would I do so) or would this suffice?

![debug](https://user-images.githubusercontent.com/12212222/54394424-337cfc80-4683-11e9-9881-01a1ce709ca5.gif)

**Comment by rin-23** [comment]
Looks like you did apply translation. What do you mean there is no translation? 
The direction of rotation doesn't matter. But if you want to change it just reverse the sign of the rotation angle.

**Comment by Geetchopra** [comment]
My translation vector is currently 0,0,0 in the above output. Doesn't that mean there is no translation?

**Comment by rin-23** [comment]
thats weird. If you dont apply translation to the moon, it will just be rotating at the origin.

**Comment by rin-23** [comment]
are you sure you are not translating  in model_view_projection.vs

**Comment by Geetchopra** [comment]
Yes, I figured out the problem! I didn't know what was causing it but i'm adding a translation in model_view_projection.vs. It's in a step before the calculation of the projection. I ended up not needing to use translate.glsl since the translate vector is hardcoded anyway.

**Comment by rin-23** [comment]
you should not use translate function in your model_view_projection.vs
translation is part of the model matrix which you compute in model.glsl
Then model matrix can be used in model_view_projection.vs

**Comment by Geetchopra** [comment]
I'm not using the function, but I just added a vector to the input vector which translates the moon. Is that also not ok? I can't seem to get translation in model.glsl to work. I tried both orders of multiplication, rotation * translation and translation * rotation.

**Comment by Geetchopra** [comment]
Just fixed it! Everything works as intended now. It was another ordering issue. Thanks a lot!
