### ISSUE TITLE
Extra resource on bump?

### ISSUE THREAD

**Issue by triangleCZH** [dilevin/computer-graphics-shader-pipeline#26]
I want to know if there are any extra resources to help with the bump surface. The algorithm for turbulence on the textbook seems unfit for bump surface.
Thanks!

**Comment by abhimadan** [comment]
Sorry about the delayed response - please see the readme of this repo for details on how to implement bump mapping, as well as section 11.4.2 of the textbook for a conceptual explanation.

**Comment by triangleCZH** [comment]
Thank you very much :D
