### ISSUE TITLE
How to use boolean is_moon in bump_height.glsl

### ISSUE THREAD

**Issue by triangleCZH** [dilevin/computer-graphics-shader-pipeline#27]
May I ask why do we need is_moon in bump_height.glsl?
Is it because we want some differences in their bumpy surface?
(i.e., without this, the bumpy surface of two spheres could be identical, maybe)

**Comment by abhimadan** [comment]
Sorry about the delayed response - you're correct, it's so that you can change the bumpiness of the surface between the earth and moon.

**Comment by triangleCZH** [comment]
Thank you for your help
