### ISSUE TITLE
Different output test-02

### ISSUE THREAD

**Issue by chenzi26** [dilevin/computer-graphics-shader-pipeline#3]
<img width="284" alt="csc418a6" src="https://user-images.githubusercontent.com/46636554/53756651-addd9d80-3e87-11e9-9802-c78a745489e3.png">
<img width="280" alt="csc418a61" src="https://user-images.githubusercontent.com/46636554/53756658-b46c1500-3e87-11e9-8db4-4404fa857d8f.png">

My output on the top does not show the edges in the back of the object comparing with reference image on the bottom. Is this a OS problem or my code is wrong?

**Comment by rarora7777** [comment]
The behaviour you report is expected. Your code should be fine.

I think that the wireframe images we've given you are showing the incorrect behaviour. I suspect that the `main.cpp` file was changed _after_ the images were generated to turn backface culling ON.
