### ISSUE TITLE
Can we use the acos() function?

### ISSUE THREAD

**Issue by charlesvong** [dilevin/computer-graphics-shader-pipeline#32]
I read an article on Perlin Noise and it suggested to use acos() to generate uniformly distributed points on a sphere, but it wasn't mentioned in the list of whitelisted functions.

The article in question: https://www.scratchapixel.com/lessons/procedural-generation-virtual-worlds/perlin-noise-part-2

**Comment by abhimadan** [comment]
`acos` and any other trig functions are OK to use.
