### ISSUE TITLE
Using the 2D vector from random2

### ISSUE THREAD

**Issue by pjsmith97** [dilevin/computer-graphics-shader-pipeline#46]
All of the resources online are generating 1D random values when calculating Perlin Noise. Why are we generating a random 2D vector?

**Comment by dilevin** [comment]
The Wikipedia page is pretty informative here: https://en.m.wikipedia.org/wiki/Perlin_noise

Under algorithm details It shows that the initial step in Perlin noise generation is to create a random gradient vector field by assigning a random 2d vector to each vertex of a grid. This vector has a random x and y direction — hence the 2d random number.

**Comment by pjsmith97** [comment]
Okay I read through that part of the page among others and I'm still confused on how we'll use the random 2D vector. In the example on the page, it's generating noise on a flat 2D plane. It mentions some "Monte Carlo" method and using a Unit cube for higher dimensions but it doesn't go into it, and the page it links to is difficult to navigate due to it needing the Wayback Machine to get the content. So far I've been following the implementation shown in the book to the best of my ability barring the smoothstep and random steps to what we've been told in the assignment:

<img width="479" alt="Screen Shot 2020-04-16 at 1 59 56 PM" src="https://user-images.githubusercontent.com/48391420/79485096-0e2b9200-7feb-11ea-835f-d16f18931936.png">

This method is the only one I've seen where they're generating a random 3D vector, but it doesn't look close to what's being implemented in random2. All others I've seen have been written for a 2D plane, not a 3D sphere. Additionally I've been looking at this page where they talk about distribution over the sphere.

<img width="721" alt="Screen Shot 2020-04-16 at 2 07 07 PM" src="https://user-images.githubusercontent.com/48391420/79485488-b5a8c480-7feb-11ea-81ee-afbd16c3a504.png">

In this one they're only using a 1D value for computing the coordinate. I don't know what I'm missing here. I should also mention that this is the method I've been using for random_direction, right now taking the magnitude of the random 2D vector and using that as the 1D value here.

**Comment by abhimadan** [comment]
We generate 2 random values instead of 3 because you can parameterize a sphere using two values: azimuth and elevation. Generating them uniformly works, but the generated points aren't uniformly distributed over the sphere - that's where the code you found comes into play. Notice that they're actually generating two random values, one for theta and one for phi.

**Comment by pjsmith97** [comment]
That was an idea I had, but didn't seem plausible. So these random values are supposed to be defined as theta and phi respectively, or would they be inserted where uniform01(generator) is (since the code mentions that we can assume the vector is uniform over [0,1]^2)

**Comment by pjsmith97** [comment]
Additionally, I should show what my actually sphere looks like right now. The color that does show up should be white for what I purposely put in my code so that's not the issue.
<img width="639" alt="Screen Shot 2020-04-16 at 3 08 48 PM" src="https://user-images.githubusercontent.com/48391420/79491066-41265380-7ff4-11ea-9f2f-18d49f84c92e.png">

From what I've been gathering, if it's segmented like it is, then there's something wrong with my smoothstep or how I use it. From the formula shown in the text book, what I understand is I'm applying the smoothstep to each member of the vector (x − i, y − j, z − k) and then multiplying them all together along with the dot product between the random direction vector and (x − i, y − j, z − k).

<img width="490" alt="Screen Shot 2020-04-16 at 3 15 17 PM" src="https://user-images.githubusercontent.com/48391420/79491680-33bd9900-7ff5-11ea-857a-d54d415eacd3.png">

Am I right so far?

**Comment by abhimadan** [comment]
> So these random values are supposed to be defined as theta and phi respectively, or would they be inserted where uniform01(generator) is (since the code mentions that we can assume the vector is uniform over [0,1]^2)

You can think of theta and phi as random variables, but they are _not_ uniformly distributed if you want points to be uniformly distributed over the sphere. The code you found essentially creates a non-uniform distribution for the angles by taking two random values as input (replace the uniform01 calls with components of random2 output), and these functions are defined in such a way that using them to compute spherical positions makes a uniform distribution over the sphere.

> From what I've been gathering, if it's segmented like it is, then there's something wrong with my smoothstep or how I use it. From the formula shown in the text book, what I understand is I'm applying the smoothstep to each member of the vector (x − i, y − j, z − k) and then multiplying them all together along with the dot product between the random direction vector and (x − i, y − j, z − k).

Correct. The textbook formula is a bit confusing, but you're essentially using the `smooth_step` values as linear interpolation weights in each dimension.

**Comment by pjsmith97** [comment]
Okay. Now the textbook also looks like it's saying I should be summing these values together for each iteration. From what I'm understanding I should be making for loops in the perlin noise function like so:

for(float i = floor(st.x); i <= floor(st.x)+1; i++)

And two other nested for loops of the same structure for y and z. From my understanding these represent the unit cube we're considering. For each iteration through these loops we add the final result (after multiplying the smoothstep and the dot product) to the total sum and then that total sum is our output for perlin noise. This is what I have implemented currently. Does that all sound correct?

Also to clarify, the seed that I'm giving the random direction function is (i, j, k), right?

**Comment by pjsmith97** [comment]
Something else to note is that my seed for perlin noise is sphere_fs_in. Is this the correct use? I heard something about applying it by vector and not face, but my understanding is this is done by the unit cube we consider in perlin noise. My main issue that I'm trying to remedy is the segmentation in my sphere. I followed the smooth function directions so that the float f is clamped and then the output is the result of 3f^2 - 2f^3. This is correct, right?

**Comment by pjsmith97** [comment]
Mainly I'm confused on whether passing sphere_fs_in is correct and if that's why I'm seeing straight lines in my sphere. And if it isn't correct, how do I get access to the vectors and not the triangles instead?

**Comment by abhimadan** [comment]
> For each iteration through these loops we add the final result (after multiplying the smoothstep and the dot product) to the total sum and then that total sum is our output for perlin noise.

Remember you need to take all 3 smooth_step values into account. However, I wouldn't recommend using a for loop over floats, since the compiler can't unroll those loops, and branching creates poor performance on GPUs. I would recommend explicitly writing out the computation for each corner of the cube.

> Also to clarify, the seed that I'm giving the random direction function is (i, j, k), right?

Yes.

> Something else to note is that my seed for perlin noise is sphere_fs_in. Is this the correct use? 

Yes, you want to compute the texture in model space so that it moves around as your spheres move around. The discontinuity is caused by a bug in your interpolation.

The formula in the textbook is a little different from what we suggest you to use, since it obscures the fact that it's really just linear interpolation in each dimension. Think of it like the following: view the cube as two squares parallel to the yz plane connected together, and interpolate along the connecting edges to get a square somewhere in between; then you view the square as two lines connected parallel to the z axis connected together, and interpolate along the connecting edges to get a line; finally, you can view the line as two points connected together, and interpolate along the connecting edge to get a point. These steps correspond to interpolations along x, then y, then z (any order works, but this is an example).

**Comment by pjsmith97** [comment]
I'm not sure I follow "take all 3 smooth_step values into account". Am I not doing that with multiplying all the values here?
![image](https://user-images.githubusercontent.com/48391420/79504103-a8e69980-8008-11ea-82b9-65d9ca82e7a1.png)

Smooth_step is my interpolation step, right? So the bug would something to do with that?

Also I just need a direct confirmation on this so I can better hone down the problem and know what I'm doing wrong: is the perlin noise output the sum of all the corner calculation results we find? What I mean is the Omega function in the screenshot, that's calculated for each corner, is the sum of those the perlin noise value?

**Comment by abhimadan** [comment]
Yeah sorry about the confusion, `smooth_step` returns a vec3, which contains the interpolation weight in each dimension, and that formula is what you return at the end. Though keep in mind that the omega function they define is a bit different from the formula we tell you to use in `smooth_step`, so that's perhaps the source of your bug.

**Comment by pjsmith97** [comment]
I don't use the smooth step they use in the textbook. This is the return value of my smooth_step function:

3 * pow(f, 2) - 2 * pow(f, 3)

f having been clamped between 0 and 1.

**Comment by pjsmith97** [comment]
Also I heard that I shouldn't be passing in negative values into smooth_step, so I've been passing in the absolute values of (x − i, y − j, z − k). Otherwise, I'm pretty sure x - (floor(x)+1) would give a negative value.

**Comment by abhimadan** [comment]
> I don't use the smooth step they use in the textbook.

Then that's the cause of your discontinuities. The textbook formula works with their omega, but not our `smooth_step`. They're related though, so look at the differences between the two and use that to figure out how you're supposed to use `smooth_step` (or alternatively, convert `smooth_step` output to omega output).

> Also I heard that I shouldn't be passing in negative values into smooth_step, so I've been passing in the absolute values of (x − i, y − j, z − k). Otherwise, I'm pretty sure x - (floor(x)+1) would give a negative value.

Yes `smooth_step` only works with positive values, but you can simply flip the order of the terms (floor(x)+1-x) to always get a positive value.

**Comment by pjsmith97** [comment]
Huh...alright. I'll look into that. Thank you.

**Comment by pjsmith97** [comment]
Okay I'm trying to figure out how to use the smooth_step we've been given. I'm having a lot of trouble. I also tried to just change the smooth step to what was given in the textbook but I couldn't get it to work. Are there any hints you can give? I don't know what I'm missing that everyone else has apparently figured out.

**Comment by abhimadan** [comment]
When t is between 0 and 1, omega(t) = 2t^3 - 3t^2 + 1 (as defined in the textbook), while your `smooth_step` is 3t^2 - 2t^3. Do you see the connection between these two formulas?

Also, check that the input to `smooth_step` is always positive. The textbook formula isn't very clear, but what it's doing is measuring the distance from the point (x,y,z) to the grid corner (i,j,k) along each axis, and using these to compute interpolation weights along each axis.

**Comment by pjsmith97** [comment]
I understand the similarities between the two. To change omega into what I have, I need to multiply that formula by -1 and subtract 1.

The other glaring difference outside of that is that when t = 0, omega = 1, and when t = 1, omega = 0. Unlike the polynomial we're told to make where t = smooth_step = 0 and t = smooth_step = 1.

So is it as simple as just applying that translation in reverse (multiply by -1 and add 1) to my smooth_step result or is there more to it than that?

**Comment by abhimadan** [comment]
I believe that's all you need to do, from what you've described (though there could be other bugs).

> The other glaring difference outside of that is that when t = 0, omega = 1, and when t = 1, omega = 0. Unlike the polynomial we're told to make where t = smooth_step = 0 and t = smooth_step = 1.

To understand this, you can view the textbook implementation of Perlin noise as a weighted sum, and the version we advocate in the assignment as interpolation. In one dimension, linearly interpolating from `a` to `b` with interpolation parameter `t` is `a*(1-t) + b*t`. `t` is selected based on starting at `a`, yet the `a` term is multiplied by `1-t`. That's what the textbook formula is doing: rather than computing the `t`, it's computing `1-t` so you can multiply it by `a` directly.

**Comment by pjsmith97** [comment]
If I were to use the mix() function, where would it come into play? I saw someone say they used it but I don't know what to use it on. It interpolates between two values. So what would be the two values in this case? I'm assuming I would be using the weight from smooth_step to interpolate between the two values.

**Comment by abhimadan** [comment]
I'm going to copy what I wrote in a previous comment, since it describes the 3 rounds of linear interpolation (one per dimension) that you need to perform. Please let me know if anything below is unclear.

> Think of it like the following: view the cube as two squares parallel to the yz plane connected together, and interpolate along the connecting edges to get a square somewhere in between; then you view the square as two lines connected parallel to the z axis connected together, and interpolate along the connecting edges to get a line; finally, you can view the line as two points connected together, and interpolate along the connecting edge to get a point. These steps correspond to interpolations along x, then y, then z (any order works, but this is an example).

**Comment by pjsmith97** [comment]
Interpolation as a concept has been confusing in general in this context but I'll do my best.

So what I'm getting is I should be interpolating (using the mix() function) multiple times, for each of the 8 corners. How do these different iterations come together, because so far I've been adding them together but I don't know for sure if that's the right method.

I saw one algorithm that's calling lerp (which I understand as another interpolation function) to connect each corner to another, going up the ladder until it calls it finally on the last two corners and that result is sent out as the perlin noise result. This one also only had one 3D interpolation vector instead of having one for each corner like the textbook does. Does any of that sound familiar?

**Comment by pjsmith97** [comment]
Alright I have something that looks at least passable, though I don't understand exactly why. It boiled down to me using the fract() function on st and passing that into smooth_step once. Then do what I described previously, I go up the ladder and use the mix() function to interpolate between the corners and then pass the end result.

<img width="641" alt="Screen Shot 2020-04-17 at 12 48 18 AM" src="https://user-images.githubusercontent.com/48391420/79530481-c7b75100-8045-11ea-8bf1-3850967c275d.png">
There's some subtle segmentation but this looks as good as I might get it at this point.

**Comment by pjsmith97** [comment]
Thank you for all your help up until this point

**Comment by abhimadan** [comment]
The "ladder approach" you described is what I was describing in my previous comment. The main reason using `fract` works is that it represents `st`'s relative position in the cube, and this relative position is used to compute interpolation weights. You use `smooth_step` because doing linear interpolation directly on `st` produces creases in the texture at cube edges (hence the name "smooth step"). Again, the textbook formula is extremely unintuitive, but it is just the fully expanded version of the math behind the interpolation.

**Comment by pjsmith97** [comment]
Hmm alright. Well it works now so that's great. Thanks again for all the help.
