### ISSUE TITLE
Question about Moon Lighting

### ISSUE THREAD

**Issue by hugoksp** [dilevin/computer-graphics-shader-pipeline#51]
I have implemented my snap to sphere and blinn-phong for the planets but the lighting on the moon does not correspond to the lightning on the planet. I am currently using normal coloring as described in the debug methods and this is what I am seeing. I would like to ask, in the correct, scenario, what should the moon look like for these positions, should the moon always have the same blue and pink color from this angle? Or am I looking at the wrong place and the normal isn't the problem?

![image](https://github.com/dilevin/computer-graphics-shader-pipeline/assets/51099136/ac3b1a6b-a90a-436d-84c4-5d26903bc1b5)
![image](https://github.com/dilevin/computer-graphics-shader-pipeline/assets/51099136/d7224021-0417-4cd5-93dc-3bfa13a8712b)

**Comment by wenzhi-guo** [comment]
I'm assuming you are calling ./shaderpipeline ../data/test-05.json with the debugging code for the normal (i.e. setting the color to 0.5+0.5*n). The color of the moon shouldn't change by this much as it rotates around the planet.

**Comment by hugoksp** [comment]
Is it supposed to look the same on the second image? If I understand correctly shouldn’t the normal always look the same if we don’t move the camera? I am a bit confused on the supposed behavior.

**Comment by wenzhi-guo** [comment]
In the second image, the moon should appear as similar color as the planet in this debugging mode.

**Comment by hugoksp** [comment]
I found the issue, I calculated my normal incorrectly without taking into consideration the center of the moon. Thanks for the help!
