### ISSUE TITLE
How to show moon in front earth?

### ISSUE THREAD

**Issue by jarenworme** [dilevin/computer-graphics-shader-pipeline#56]
my moon is hidden behind the earth. How do I get it to orbit?

https://github.com/dilevin/computer-graphics-shader-pipeline/assets/90414176/46e78a5d-535f-48c3-a9a3-0129a56a44ab

**Comment by RudainaK** [comment]
it looks like your moon is rotating behind the earth (and seems to go inside it), so something is likely with your rotation or translation

**Comment by wenzhi-guo** [comment]
yes, I agree with the above comment. Double check with your transformation matrix and projection code.

**Comment by jarenworme** [comment]
Thanks, it was because the earth object was not receiving the functions in model
