### ISSUE TITLE
Bump height bounds

### ISSUE THREAD

**Issue by ElliotP-K** [dilevin/computer-graphics-shader-pipeline#58]
In the description of bump height it says: "elevation adjust along normal (values between -0.1 and 0.1 are reasonable."

is -0.1 to 0.1 the limits or can I have values from -0.5 to 0.5? a max abs bump height of 0.1 is kind of small and makes for less interesting topography so I was hoping to use the limits I specified

**Comment by wenzhi-guo** [comment]
Considering the size of the moon and planet, values in [-0.1, 0.1] should already create very noticeable changes. But of course, depending on what effects you want to achieve, you can use larger values, these are not hard bounds for the function).
