### ISSUE TITLE
What is the graphics pipeline?

### ISSUE THREAD

**Issue by Kevinktv** [dilevin/computer-graphics-shader-pipeline#68]
Hello,

So I'm a bit confused about the overall pipeline and organization of code. Could someone confirm my understanding?

### So the first step is vertex shading (Ex: model_view_projection.vs)
This takes in as input the coordinates in object space and projects them onto the screen/clip space.

### The next step is tesselation control: 
This takes in as input the 2d coordinates output from the vertex shader of all three corners of the triangle and subdivides it.

### The next step is tesselation evaluation shader:
This takes in the vertices generates from tcs (gl_Tes_coord) (2d vectors in homogenous space again) and the the corner infos of original triangle (pos_es_in) and interpolates the values to these new points generates.

**Question about the above 2 steps** (tcs and tes) on going through the code, the inputs are in object space? Like why are we doing the object transformation in tes again? Is there a reason? Is the vertex shading a redundant step or something?

### Finally, I guess rasterization where the coloring and stuff happen.

Could you confirm whether my understanding of the three steps are correct? In particular the input and output shapes of each step and the question that is bolded?

Thanks!

**Comment by mengf821** [comment]
Hello Kevinktv,

Your understanding is mostly correct. Let's take a look at each stage of the graphics pipeline.

The vertex shader takes a vertex input in model space and transforms it into an output. If no other subsequent operations are done, this output is often in clip space, but it does not have to be. In `test-04`, for example, the vertex shader is a pass-through shader, and the majority of the transformations are handled by `snap-to-sphere.tes`. Additionally, the output is a 4D vector, not a 2D vector.

When used (not as a pass-through shader), the tessellation control shaders in our example take input from model space and subdivide patches (triangles in our example) according to your settings.

The tessellation evaluation shaders, when used (and not as pass-through shaders), can be treated as effectively a vertex shader but operating on the subdivided vertex coordinates. Your explanation is a bit confusing to me here. `gl_TessCoord` is a barycentric coordinate used to obtain the position of the current subdivided coordinate. It is a `vec3` and not a homogeneous coordinate.

We are not doing model-view-projection transformations in TES **again**. If you read the JSON files, in all cases where model-view-projection transformations are done in TES, we use a pass-through shader for the vertex shader. This means you are correct that the input to the tessellation shaders, when they are not pass-through shaders, is in model space.

The variable `gl_Position` is in clip space homogenous coordinate which the GPU takes and interpolates the information needed for the fragment shader.

Maybe [this post](https://learnopengl.com/Getting-started/Coordinate-Systems) explains everything a bit better. You can also refer to the textbook for details on how transformations are done in the graphics pipeline.
