### ISSUE TITLE
Question about requirement for procedural_color.glsl

### ISSUE THREAD

**Issue by IgorStempen** [dilevin/computer-graphics-shader-pipeline#7]
Hi,

I know that the explanation for procedural_color.glsl says to be creative, but I wanted to know if there were any strict requirements that have to be met for this function?

I am having trouble making mine look exactly like the example. Would an implementation such as the one that I currently have be sufficient?

<img width="321" alt="capture" src="https://user-images.githubusercontent.com/14172179/53983167-9fd88880-40e4-11e9-8577-b8fbac299e0a.PNG">

**Comment by rin-23** [comment]
yes it will be hard to make yours look exactly same. Yours looks fine to me.

**Comment by csc418-anon** [comment]
I'm kind of stuck on this part. Are we supposed to interpolate the point from a 2d grid, or a 3d cube?

My sphere kind of looks like this, and it's just brutal. I feel like I'm over doing it. I'm trying to interpolate the  3d point over a 3d cube using the random vectors as vertices.

There's sigmoidal shapes on the surface, so it's kind of working?  (I disabled phong)....any ideas? 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/48340920/54004212-c5848280-4122-11e9-8901-b8ca177e52e1.png">

**Comment by rin-23** [comment]
its 3d grid

This is a good resource for perlin noise - https://www.scratchapixel.com/lessons/procedural-generation-virtual-worlds/perlin-noise-part-2

This is a good intro as well - https://www.scratchapixel.com/lessons/procedural-generation-virtual-worlds/procedural-patterns-noise-part-1
