### ISSUE TITLE
Test 01 Different Color

### ISSUE THREAD

**Issue by EgeSayin** [dilevin/computer-graphics-shader-pipeline#71]
Hi, I installed OpenGL on my Ubuntu wsl. This is what I get when I run glxinfo | grep OpenGL
![image](https://github.com/user-attachments/assets/b7d74b40-ec13-468e-965c-27e7b71bd62d)
I didn't get any errors when running cmake and make. However, when I run tests 01, I get different color
![image](https://github.com/user-attachments/assets/d915bb80-2511-4ccd-a690-6bba76ca907b)
Didn't edit anything. What could be the issue? Thanks

**Comment by mengf821** [comment]
Hello,

If you did not change anything in the starter code this is most likely an environment issue. Can you try it on Windows without WSL? If that doesn't work you might need to consider trying it on the school machines.
