### ISSUE TITLE
Test 4 Looks right, but not Test 5

### ISSUE THREAD

**Issue by EgeSayin** [dilevin/computer-graphics-shader-pipeline#72]
Hi, My test 4 looks like this 
![image](https://github.com/user-attachments/assets/956a97ae-0719-4f3b-b4a9-ac94895c8530)
![image](https://github.com/user-attachments/assets/d6ca97df-7f72-4c51-af7f-18b2e39cb583)
But my test 5 looks like this 
![image](https://github.com/user-attachments/assets/c05e32c3-f4b7-4a0c-b2a0-d2f3cb74a790)
![image](https://github.com/user-attachments/assets/7ed4e6da-b197-4a59-989c-f73b7dcc1708)

What could be the issue? Thank you.

**Comment by mengf821** [comment]
Hello,

My guess is that your normals might not be transformed properly? If you still have problems after examinig that feel free to send your code to me via the TA email.

**Comment by EgeSayin** [comment]
Thank you, you were right. I was using the wrong coordinates when calculating the normal.
