### ISSUE TITLE
Different Animation Speed 

### ISSUE THREAD

**Issue by FalakR** [dilevin/computer-graphics-shader-pipeline#75]
Hi, it might not be as significant but I think for my output, the speed of planet is relatively lesser than that in the expected output. I understand that we dealt with this in model.glsl but I'm not really sure if that also meant setting the speed for the planet. Nonetheless, not sure how to fix it or should it really matter. 

For reference, below is a screen recording of my output- 

https://github.com/user-attachments/assets/8da6c147-dec6-464f-a8fc-394220702469

P.S- I'm running ./shaderpipeline ../data/test-05.json

**Comment by mengf821** [comment]
When you talk about the "speed of the planet" are you referring to the speed of the light source? If so then I don't think it's specified anywhere in the assignment, but you should double check that. If it's not specified then it's up to you what you want to be set as.

**Comment by FalakR** [comment]
Yeah, I mean the speed of light source. Yeah I don't think it's specified anywhere, I checked the tutorial slides and assignment handout both. Sounds good, thanks!
