### ISSUE TITLE
Are we allowed to use "dot" function?

### ISSUE THREAD

**Issue by LatencyWrangler** [dilevin/computer-graphics-shader-pipeline#77]
The "dot" function is not listed in the whitelist of the README, so I'm not sure if we're allowed to use it, but I'm not sure how else to compute the dot product (e.g. in blinn_phong.glsl)?

**Comment by mengf821** [comment]
You are allowed to use the `dot` function. You can also use `cross` and `mix` if you need it.

However, even if neither are available you should be able to implement each of them pretty easily.

**Comment by LatencyWrangler** [comment]
I was too focused on how to accomplish it with the whitelist functions that it completely slipped my mind that I could've done it manually. Lack of sleep from working on multiple assignments this week must've turned my brain to mush :sweat_smile:
