### ISSUE TITLE
Perlin noise 

### ISSUE THREAD

**Issue by harrychy8** [dilevin/computer-graphics-shader-pipeline#8]
![capture](https://user-images.githubusercontent.com/15678482/54009332-6e89a800-4138-11e9-9a95-bb94da455bd8.PNG)
My earth got cut into 8 parts, not sure why this happened.
Below is my mix code 
![capture](https://user-images.githubusercontent.com/15678482/54009380-96790b80-4138-11e9-9ade-16e4da3f63ea.PNG)

**Comment by csc418-anon** [comment]
I posted a similar issue I was having in issue #7.  Seems like I was doing it some-what right, just got my math wrong, but unfortunately both of us have similar problems. 

Follow up question for you. How are you getting the color? I'm multiplying the Perlin Noise by the diffuse, and it looks there isn't any color. It may seem like an obvious question, but having trouble validating my math if the color isn't showing. Where am I screwing up? Been stuck on this for longer than usual....

**Comment by ACalza** [comment]
@csc418-anon You gotta mess around with functions inside procedural colour. For example mess around with sin and cos functions inside the diffuse, that's probably why you're getting messed up colours.

I have the same issue, except it's kind of split in triangles....I'm posting here just to get notifications lmao. But I think it may have to do with the random_vector function. I'm tinkering with it, and it seems to look better after using PI.

<img width="469" alt="image" src="https://user-images.githubusercontent.com/3921291/54057430-f4513600-41c0-11e9-8af7-985bdaaf92df.png">

EDIT: @harrychy8  

Your code looks fine, however I think you're mixing in the wrong order, IE d0, g0 might be reversed. I tried reversing it for the sake of it and I get exactly what you get:

<img width="431" alt="image" src="https://user-images.githubusercontent.com/3921291/54057747-ccae9d80-41c1-11e9-86b1-042c5d1c5c59.png">

**Comment by rin-23** [comment]
your code looks correct. Are you sure each xyz values of your gradient varies between [-1,1] ?
also are you sure your d* vectors are calculated properly. 
I think smth is wrong with one those vectors.

**Comment by harrychy8** [comment]
> @csc418-anon You gotta mess around with functions inside procedural colour. For example mess around with sin and cos functions inside the diffuse, that's probably why you're getting messed up colours.
> 
> I have the same issue, except it's kind of split in triangles....I'm posting here just to get notifications lmao. But I think it may have to do with the random_vector function. I'm tinkering with it, and it seems to look better after using PI.
> 
> <img alt="image" width="469" src="https://user-images.githubusercontent.com/3921291/54057430-f4513600-41c0-11e9-8af7-985bdaaf92df.png">
> 
> EDIT: @harrychy8
> 
> Your code looks fine, however I think you're mixing in the wrong order, IE d0, g0 might be reversed. I tried reversing it for the sake of it and I get exactly what you get:
> 
> <img alt="image" width="431" src="https://user-images.githubusercontent.com/3921291/54057747-ccae9d80-41c1-11e9-86b1-042c5d1c5c59.png">

I tried to reverse them but I got the same thing. I really do not know what is going on LOL. I have tried to rewrite this part for over 4 times.

**Comment by ACalza** [comment]
Wherever you're splitting the fractional and non-fractional position is where you're messing up. Your math was probably right the entire time. But I assume you figured this out by now, but might as well post just in case.
