### ISSUE TITLE
could not create glfw window

### ISSUE THREAD

**Issue by Allof02** [dilevin/computer-graphics-shader-pipeline#81]
![image](https://github.com/user-attachments/assets/e3477cd1-ee9c-4d16-9131-0f39a06fd81b)

I'm running test-01 but getting this error.

**Comment by mengf821** [comment]
Dear @Allof02 ,

I'm not quite sure why this is the case. It's hard to get these issues resolved, especially with so little information. :crying_cat_face: 

Would you be able to try it on the lab machines?

**Comment by Allof02** [comment]
Ahhh it was due to gpu driver mismatching. It works after rebooting the system.
